### PR TITLE
Update color schemes using the latest Base16 schemes

### PR DESCRIPTION
**Pull request by tknarr**
Updated the preset schemes with the latest Base16 schemes.
Added a script to set PowerShell's syntax highlighting colors to Base16's conventions.
Cleaned up end-of-line characters to be Windows CRLF (I edited the files on Linux and it was trying to switch to newlines and messing up the .png files).

### CODE REVIEW

**Comment by tknarr** [comment]
I replaced the presets with the new Base16 ones. If you'd prefer to add the new ones without replacing the old ones, I can create a new PR that way.

**Comment by lukesampson** [comment]
Thanks but can you provide a bit more background about what this does? I haven't been paying attention lately so I'm not sure what the "latest Base16" schemes are.

Will this break things for existing users? Are there any upgrade steps that need to be done? If so, it might be worth doing new presets as you suggested, so that users can opt in to the new behaviour.

**Comment by tknarr** [comment]
There shouldn't be any non-obvious new behavior, and it won't break anything for people who've already set a color scheme. The only change in behavior is that the preset color schemes available when you're setting a preset scheme change.

Latest Base16 has changed and updated the set of available schemes. There's several been added, and they changed how they handle light and dark schemes to not automatically try to create the second variant if only one's provided. I added `concfg` support to the Base16 builder and used that to regenerate the preset schemes based on what was in the Base16 scheme repositories.

I left the Windows console and PowerShell window default preset schemes alone other than renaming the Windows console default one to avoid conflict with the similarly-named Base16 scheme.

**Comment by lukesampson** [comment]
Thanks, this is sounding good but can you provide a link where I can read more about the new Base16 schemes? I'm confused about who the "they" is that changed how light and dark themes are handled. Is this coming from somewhere in Microsoft or is it a Linux / cross platform thing?

**Comment by tknarr** [comment]
https://github.com/chriskempson/base16

**Comment by lukesampson** [comment]
Thanks, let's try it.

**Pull request merged**
